# Day 10 Assignment

In [1]:
import numpy as np
import pandas as pd

## Question 1:
### Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
a1=np.random.randn(6)
a1

array([ 0.84582868, -1.71750493, -0.55727953,  1.12350212,  0.86414115,
        0.63640019])

In [3]:
a2=np.random.randn(6)
a2

array([ 0.11329038,  0.7334501 , -0.80391402,  0.69079719,  1.04335249,
       -0.47431314])

In [4]:
np.greater(a1,a2) # a1 is greater than a2

array([ True, False,  True,  True, False,  True])

In [5]:
np.greater_equal(a1,a2)  # a1 is greater than equal to a2

array([ True, False,  True,  True, False,  True])

In [6]:
np.less(a1,a2) #  a1 is less than a2

array([False,  True, False, False,  True, False])

In [7]:
np.less_equal(a1,a2)  # a1 is less than equal to a2

array([False,  True, False, False,  True, False])

## Question 2:
### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [8]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.full([10,10],5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

## Question 3:
### Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [11]:
arr1=np.array([[31,23,29],
               [51,43,89]])
arr1

array([[31, 23, 29],
       [51, 43, 89]])

In [12]:
arr1.sum() # sum of all the elements of arr1

266

In [13]:
arr1.sum(axis=1) # sum of each row of arr1

array([ 83, 183])

In [14]:
arr1.sum(axis=0) # sum of each column of arr1

array([ 82,  66, 118])

## Question 4:
### Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [15]:
arr1

array([[31, 23, 29],
       [51, 43, 89]])

In [16]:
arr2=np.array([[11,21,34],
             [21,43,61]])
arr2

array([[11, 21, 34],
       [21, 43, 61]])

In [17]:
np.add(arr1,arr2) # element-wise addition of two array

array([[ 42,  44,  63],
       [ 72,  86, 150]])

In [18]:
np.subtract(arr1,arr2) # element-wise subtraction of two array

array([[20,  2, -5],
       [30,  0, 28]])

In [19]:
np.multiply(arr1,arr2) # element-wise multiplication of two array

array([[ 341,  483,  986],
       [1071, 1849, 5429]])

In [20]:
np.divide(arr1,arr2) # # element-wise division of two array

array([[2.81818182, 1.0952381 , 0.85294118],
       [2.42857143, 1.        , 1.45901639]])

## Question 5:
### Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [21]:
x=np.array([0,30,45,60,90])
x

array([ 0, 30, 45, 60, 90])

In [22]:
np.sin(x * np.pi / 180) # sine array of angles given in degree

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [23]:
np.cos(x * np.pi / 180) # cosine array of angles given in degree

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [24]:
np.tan(x * np.pi /180) # tangent array of angles given in degree

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

## Question 6:
### Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [25]:
d= {'Age': pd.Series([22,43,65],index=[113,141,172]),
    
    'Income($)': pd.Series([200,100,440,120,700],index=[121,176,113,165,172])}

In [26]:
d

{'Age': 113    22
 141    43
 172    65
 dtype: int64, 'Income($)': 121    200
 176    100
 113    440
 165    120
 172    700
 dtype: int64}

In [27]:
df=pd.DataFrame(d)
df

Age  Income($)
113  22.0      440.0
121   NaN      200.0
141  43.0        NaN
165   NaN      120.0
172  65.0      700.0
176   NaN      100.0

## Question 7:
### Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [28]:
d1= {'Id':pd.Series([11,12,13,14,15,16]),
     
    'Name': pd.Series(['Rohan','Rehana','Herry','Selin','Nimo']),
    
    'Age': pd.Series([22,43,65,54]),
     
    'Score': pd.Series([65,87,44,75,77,79])
    
    }

In [29]:
df1=pd.DataFrame(d1)
df1

Id    Name   Age  Score
0  11   Rohan  22.0     65
1  12  Rehana  43.0     87
2  13   Herry  65.0     44
3  14   Selin  54.0     75
4  15    Nimo   NaN     77
5  16     NaN   NaN     79

In [30]:
df1['Name'] # selecting the Name column from df1

0     Rohan
1    Rehana
2     Herry
3     Selin
4      Nimo
5       NaN
Name: Name, dtype: object

In [31]:
df1['Score']  # selecting the Score column from df1

0    65
1    87
2    44
3    75
4    77
5    79
Name: Score, dtype: int64

## Question 8:
### Write a Pandas program to join the two given dataframes along rows and assign all data.

In [32]:
d2= {'Id':pd.Series([11,12,13,14,15,16]),
    
    'Sex': pd.Series(['M','F','M','F']),
    
    'Income($)': pd.Series([200,100,440,120,700])}

In [33]:
df2=pd.DataFrame(d2)
df2

Id  Sex  Income($)
0  11    M      200.0
1  12    F      100.0
2  13    M      440.0
3  14    F      120.0
4  15  NaN      700.0
5  16  NaN        NaN

In [34]:
# joining two dataframes df1 & df2
join_df=df1.merge(df2,how='inner',on='Id')
join_df

Id    Name   Age  Score  Sex  Income($)
0  11   Rohan  22.0     65    M      200.0
1  12  Rehana  43.0     87    F      100.0
2  13   Herry  65.0     44    M      440.0
3  14   Selin  54.0     75    F      120.0
4  15    Nimo   NaN     77  NaN      700.0
5  16     NaN   NaN     79  NaN        NaN

## Question 9:
### Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [35]:
join_df.isnull().any()

Id           False
Name          True
Age           True
Score        False
Sex           True
Income($)     True
dtype: bool

## Question 10:
### Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [36]:
data=[12,31,45,21,89]

In [37]:
sr=pd.Series(data)
sr

0    12
1    31
2    45
3    21
4    89
dtype: int64