# Day 10 Assignment

In [1]:
import numpy as np

## Question 1:
### Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
a1=np.random.randn(6)
a1

array([ 0.27186691, -0.79670701,  0.48174398,  0.32783148, -0.04446057,
       -0.02079833])

In [3]:
a2=np.random.randn(6)
a2

array([ 0.36932312,  0.30992435,  1.54363859, -0.77973666, -0.90074291,
       -0.19800766])

In [4]:
np.greater(a1,a2) # a1 is greater than a2

array([False, False, False,  True,  True,  True])

In [5]:
np.greater_equal(a1,a2)  # a1 is greater than equal to a2

array([False, False, False,  True,  True,  True])

In [6]:
np.less(a1,a2) #  a1 is less than a2

array([ True,  True,  True, False, False, False])

In [7]:
np.less_equal(a1,a2)  # a1 is less than equal to a2

array([ True,  True,  True, False, False, False])

## Question 2:
### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [8]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.full([10,10],5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

## Question 3:
### Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [11]:
arr1=np.array([[31,23,29],
               [51,43,89]])
arr1

array([[31, 23, 29],
       [51, 43, 89]])

In [12]:
arr1.sum() # sum of all the elements of arr1

266

In [13]:
arr1.sum(axis=1) # sum of each row of arr1

array([ 83, 183])

In [14]:
arr1.sum(axis=0) # sum of each column of arr1

array([ 82,  66, 118])

## Question 4:
### Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [15]:
arr1

array([[31, 23, 29],
       [51, 43, 89]])

In [16]:
arr2=np.array([[11,21,34],
             [21,43,61]])
arr2

array([[11, 21, 34],
       [21, 43, 61]])

In [17]:
np.add(arr1,arr2) # element-wise addition of two array

array([[ 42,  44,  63],
       [ 72,  86, 150]])

In [18]:
np.subtract(arr1,arr2) # element-wise subtraction of two array

array([[20,  2, -5],
       [30,  0, 28]])

In [19]:
np.multiply(arr1,arr2) # element-wise multiplication of two array

array([[ 341,  483,  986],
       [1071, 1849, 5429]])

In [20]:
np.divide(arr1,arr2) # # element-wise division of two array

array([[2.81818182, 1.0952381 , 0.85294118],
       [2.42857143, 1.        , 1.45901639]])

## Question 5:
### Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [21]:
x=np.array([0,30,45,60,90])
x

array([ 0, 30, 45, 60, 90])

In [22]:
np.sin(x * np.pi / 180) # sine array of angles given in degree

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [23]:
np.cos(x * np.pi / 180) # cosine array of angles given in degree

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [24]:
np.tan(x * np.pi /180) # tangent array of angles given in degree

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])